name: cuncurrency
on: workflow_dispatch
concurrency:
  group: cuncurrency-testing
  cancel-in-progress: true
jobs:
  test-timeout:
    runs-on: ubuntu-latest
    steps:
      - name: Testing timeout
        run: sleep 25
        timeout-minutes: 1
