name: Docker test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      customMysql:
        image: mysql
    container:
      image: node
      env:
        NODE_ENV: test
    steps:
      - name: Display server image
        run: echo '${{ toJSON(job.services) }}'
      - name: Docker node version
        run: |
          node -v
          cat /etc/os-release
      - name: Docker new version
        uses: docker://node:18-buster-slim
        with:
          args: -v
