name: Fifteen workflow
on: [push]
jobs:
  run-first-commnads:
    runs-on: ubuntu-latest
    steps:
      - name: MAth expression
        run: expr 1 + 1 > math.txt
      - name: UPload math file
        uses: actions/upload-artifact@v3
        with:
          name: math.txt
          path: math.txt
