name: fifth workflow
on:
  issues:
    types: [edited, deleted]
  pull_request:
    types: [closed]
jobs:
  run-first-commnads:
    runs-on: ubuntu-latest
    steps:
      - name: Event vars
        run: |
          echo "name: fifth workflow"
          echo $GITHUB_SHA
          echo $GITHUB_REF
