name: first workflow
on: workflow_dispatch
jobs:
  run-first-commnads:
    runs-on: ubuntu-latest
    steps:
      - name: echo a
        run: echo "a first command"
      - name: echo b
        run: echo "b second command"
      - name: Multi line commnad
        run: |
          node -v
          npm -v
          python -V
          pip -V
