name: Fourteen workflow
on: [workflow_dispatch]

jobs:
  run-fourteen-commnads:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Custom action
        uses: ./.github/actions/cache-node-modules
