name: Fourteen workflow
on: [workflow_dispatch]

jobs:
  run-fourteen-commnads:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Custom action
        id: cache
        uses: ./.github/actions/cache-node-modules
        with:
          caching: "false" # default: true
      - name: Display output caching
        run: echo '${{ toJSON(steps.cache.outputs) }}'
