name: fouth workflow
on:
  workflow_run:
    workflows: [third workflow]
    types:
      - completed
jobs:
  success-commnads:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Hellow from fouth workflow"
        run: echo "third workflow run successfully"
  failure-commnads:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Hellow from fouth workflow"
        run: echo "third workflow run failure"
