name: nine workflow
on:
  repository_dispatch:
    types: [test]

jobs:
  run-eight-commnads:
    runs-on: ubuntu-latest
    steps:
      - name: Event vars
        run: |
          echo "Title: ${{ github.event.client_payload.titleCustom }}"
