name: seventh workflow
on:
  schedule:
    - cron: "*/2 * * * *"
jobs:
  run-first-commnads:
    runs-on: ubuntu-latest
    steps:
      - name: Event vars
        run: |
          echo "name: sixth workflow"
          echo $GITHUB_SHA
          echo $GITHUB_REF
