name: third workflow
on: [push]
jobs:
  run-first-commnads:
    runs-on: ubuntu-latest
    steps:
      - name: List file and copy repo
        run: ls -a
      - uses: actions/checkout@v4
      - name: List file
        run: ls -a
