name: third workflow
on: [push]
jobs:
  run-first-commnads:
    runs-on: ubuntu-latest
    steps:
      - name: List file before
        run: ls -a
      #- uses: actions/checkout@v4
      - name: copy repo
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@/github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout origin/main
      - name: List file after
        run: ls -a
