name: twelve workflow
on: [push]

jobs:
  run-first-commnads:
    runs-on: ubuntu-latest
    environment: "staging"
    steps:
      - name: Our vars & secrets
        run: |
          echo '${{ vars.STATUS }}'
          echo '${{ secrets.PASSWORD }}'
